### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by lriesebos** [fmagin/networkx-stubs#4]
@fmagin @gjulianm , I am potentially interested in using your stubs for a project, but for that I need your stubs to be licensed. Would you mind adding a license to the project? Preferably it would be the same license as used for networkx.

**Comment by fmagin** [comment]
Just added a license, though I am not sure if you also require explicit confirmation from @gjulianm that his contributions are also licensed as BSD 3-Clause. I am assuming that they would not have a problem with it, but if that is an issue I can also live with reverting their changes so I hold fully copyright and put their changes in a branch that doesn't have a license until they approve a merge.

I am curious what kind of project you are working on where the stubs help. I want to emphasize again that most of the repo is just the auto generated stubs from stubgen and they aren't even necessarily in sync with the upstream networkx release anymore as I don't know how to automatically test if they are still in sync.

**Comment by gjulianm** [comment]
It's not an issue at all on my part, I'm ok with my contributions being BSD-3.

**Comment by lriesebos** [comment]
Tnx, appreciate the quick response!

So I am considering to use your stubs for https://gitlab.com/duke-artiq/dax instead of using my own local and very limited stubs. We do not use a lot of networkx functionality, mainly `DiGraph`. I have not inspected your stubs in detail, but if you consider them outdated, I might want to reconsider that choice.

I guess that stubs could maybe be tested in a CI environment by using `inspect`, but I have never tried that. But obviously it also depends on your interest to maintain this repo if this is worth investigating. Let me know what your thoughts are!

**Comment by fmagin** [comment]
There were already some discussions in the actual networkx repo and it seems like they are open to merging type annotations, so I will probably focus my efforts there and hopefully make this repo obsolete.

The files in the repo are largely the auto generated stubs, I only really annotated the basics of `DiGraph` and gjulianm added annotations for MultiGraphs.

https://github.com/fmagin/networkx-stubs/compare/0b26cd3..master should be a decent overview of the changes that weren't the initial addition of the auto generated stubs

**Comment by lriesebos** [comment]
Ok, that is good to know. In that case, I will probably not start using these stubs now and instead wait until any annotations are merged into the networkx repo. Tnx for the heads up!
