### ISSUE TITLE
How to use this repository?

### ISSUE THREAD

**Issue by a-t-0** [fmagin/networkx-stubs#5]
Thank you for your work Florian! I was trying to add this networkx stub to a project, to try to ensure `mypy` is able to verify networkx object typing with:
```
def simulate_network_on_lava(G: nx.Graph(), t: int) -> None:
```
However, it is not quite clear how I could ensure mypy finds your stubs. Do you perhaps have a suggestion on how to use your work?

**Comment by fmagin** [comment]
Should be enough to just `pip install` the package. e.g. run `pip instlal https://github.com/fmagin/networkx-stubs/archive/refs/heads/master.zip` and it should install the package `networkx-stubs` inside the current venv and all relevant tools (`mypy`, IDEs like PyCharm) should use it automatically.

**Comment by a-t-0** [comment]
Thank you for your explanation and quick response! As a side-note, I noticed that the line I wrote:
```
def simulate_network_on_lava(G: nx.Graph(), t: int) -> None:
```
was wrong. It should have been:
```
def simulate_network_on_lava(G: nx.Graph, t: int) -> None:
```
Changing it also allowed `mypy` to recognise the typing correctly.
